# Generated by Django 2.1.7 on 2019-02-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discounttime', models.DateField()),
                ('describ', models.TextField()),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salah.Depart')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salah.Products'),
        ),
    ]
