# Generated by Django 2.1.7 on 2019-02-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
