# Generated by Django 2.1.7 on 2019-02-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salah', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(max_length=50),
        ),
    ]
