# Generated by Django 2.1.7 on 2019-03-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salah', '0005_auto_20190227_1315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='depart',
            name='token',
            field=models.CharField(default='8dcb8ea967601761113feb25d24b477e331fff4e', max_length=200),
        ),
        migrations.AddField(
            model_name='images',
            name='token',
            field=models.CharField(default='8dcb8ea967601761113feb25d24b477e331fff4e', max_length=200),
        ),
        migrations.AddField(
            model_name='products',
            name='token',
            field=models.CharField(default='8dcb8ea967601761113feb25d24b477e331fff4e', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
    ]
